// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHQJEegAQxRiIvpr0lG7o8ODVT3tH48Vo',
    appId: '1:870284568222:web:9d7b4f56a98e101b2dfd8f',
    messagingSenderId: '870284568222',
    projectId: 'todo-app-tas',
    authDomain: 'todo-app-tas.firebaseapp.com',
    storageBucket: 'todo-app-tas.firebasestorage.app',
    measurementId: 'G-715KR36XP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxPdUOJV1vLHN8178VbnL5yBveD8c84M',
    appId: '1:870284568222:android:f55ec6648ab176b52dfd8f',
    messagingSenderId: '870284568222',
    projectId: 'todo-app-tas',
    storageBucket: 'todo-app-tas.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHQJEegAQxRiIvpr0lG7o8ODVT3tH48Vo',
    appId: '1:870284568222:web:a3bfef62c347afbb2dfd8f',
    messagingSenderId: '870284568222',
    projectId: 'todo-app-tas',
    authDomain: 'todo-app-tas.firebaseapp.com',
    storageBucket: 'todo-app-tas.firebasestorage.app',
    measurementId: 'G-5GP47Z9H8N',
  );
}
